### ISSUE TITLE
Suggestion: Add a checking in the Event Handlers for the call of the BaseMethod.

### ISSUE THREAD

**Issue by sampetrosov** [Acumatica/Acuminator#380]
Could you add validation to check if the event handler invokes the base method or no and show a warning if it doesn't invoke?

For example, the below method should show a warning that the base method is blocked because it is not invoked.
``` csharp
        protected virtual void SOOrder_RowUpdated(PXCache cache, PXRowUpdatedEventArgs e, PXRowUpdated baseMethod)
        {
            if (e.Row is SOOrder row)
            {
                 row.Description = "Test123";
            }
        }
```

**Comment by SENya1990** [comment]
@sampetrosov hi. We already discussed similar suggestion internally. There are many cases where we actually need to suppress the call to base event handler completely. The event handler without a delegate parameter won't help here because for such handlers the base method will be called automatically.
How should we treat the following code:
```csharp
protected virtual void SOOrder_RowUpdated(PXCache cache, PXRowUpdatedEventArgs e, PXRowUpdated baseMethod)
 {
            if (e.Row is SOOrder row)
            {
                 row.Description = "Test123";
            }
           
            if (ShouldCallBase(row))
                  baseMethod(cache, e);
}
```

The baseMethod here is not called on every execution path. It will be called only if the condition is true and this is done deliberately. 
In general the purpose of event handler with delegate parameter is to provide fine-grained control over the call to the base method. If you don't need it you can consider event handler without delegate parameter which will be called automatically.
