### ISSUE TITLE
Potential Accidental synchronous call in async code

### ISSUE THREAD

**Issue by ShadowFiendZX** [Acumatica/Acuminator#397]
I'm not sure if this is something I should create a PR for, if it is I can push my changes and create one.

The other night I pulled down the code to look into an issue we've been having in the office, and I got a warning on compile about Acuminator\Acuminator.Vsix\Coloriser\AsyncTagging\BackgroundTagging.cs.
 In AfterTaggingActionAsync there is :
` Shell.ThreadHelper.JoinableTaskFactory.Run(tagger.RaiseTagsChangedAsync);` the compiler suggested : `await Shell.ThreadHelper.JoinableTaskFactory.RunAsync(tagger.RaiseTagsChangedAsync);`

I haven't looked too much into the implementation, so this could have been intentional, as I've seen it done in other places with preprocessor directives to disable the warning.

I had changed it locally in the hopes that it'd fix the error we've been getting, but the change appeared not to affect anything at all.

The error in question may have been on Microsoft's side. I debugged Acuminator with "Just my code" disabled and saw that they were disposing an object then trying to access it to get error information. The [ticket](https://developercommunity.visualstudio.com/t/Getting-StreamJsonRpcConnectionLostExce/1349881) I opened before I noticed that the logs mentioned Acuminator was recently marked as duplicate, with the related [ticket](https://developercommunity.visualstudio.com/t/IntelliSense-is-extremely-slow-and-not-r/1365381) having been marked as fixed last night.

**Comment by SENya1990** [comment]
Hi @ShadowFiendZX . Thanks for your input! We use VS SDK Roslyn analyzers for Acuminator integration with Visual Studio. 
They are added as a nuget package, that's why you received them when you downloaded and built Acuminator. These analyzers help us find issues with VS threading model (it has non-standard threading, you can read more [here](https://github.com/Acumatica/Acuminator/blob/dev/docs/dev/CodingGuidelines/CodingGuidelines.md#task-blocking)) However, they are not perfect and in complex scenarios display false errors. Here you received unsuppressed error from one of these analyzers - to run the code asynchronously to avoid potential deadlocks and improve UI responsiveness. However, the code with this warning is already executed in the asynchronous context.  We will try to investigate this warning and rework the code if there are performance gains or suppress it. But it is highly unlikely that Acuminator causes your problem.

Regarding your main issue issue about StreamJsonRpc and VS logs mentioning Acuminator - Acuminator is subscribed on all VS unhandled exceptions and writes them to VS activity log. This was done since the earlier versions of Acuminator because VS SDK lacks documentation in some places and we have to learn by trial and error. Still it captures many of the VS own exceptions.

**Comment by SENya1990** [comment]
A bit more on StreamJsonRpc  problem since I also encounter it from time to time.
In the latest Visual Studio versions all Roslyn static code analysis started to be run out of process in a separate process "ServiceHub.RoslynCodeAnalysisService". This is a default mode for the latest updates of VS 2019.
The option is called "Use 64-bit process for code analysis" in Visual Studio (Tools -> Options -> Text Editor -> C# -> Advanced -> Analysis). You can try disabling it but it will probably decrease your VS performance significantly. Visual Studio 2019 is a 32 bit application and for the static code analysis to be fast it requires more memory than 32 bit process can provide therefore out of process analysis was introduced. 

However, out of process analysis requires inter process communication and is a quite complex to do. I have started to encounter much more errors after introduction of this feature. Many of them look somewhat related to the inter process communication like StreamJsonRpc (it seems to me that RPC stands for the remote procedure call) Or `ObjectDisposedException` and `ConnectionLostException`:
![изображение](https://user-images.githubusercontent.com/7687400/121550435-686d8a80-ca17-11eb-9bda-d30d5603196f.png)

The one unfortunate thing we will be changing is that the log message contains phrase `"ACUMINATOR CAUSED ERROR"`. During the early days of Acuminator this was 99% of all unhandled VS errors but now unfortunately the situation changed

**Comment by SENya1990** [comment]
The warning reported by the VS SDK analyzers was investigated and the code was reworked to be asynchronous in this PR:
https://github.com/Acumatica/Acuminator/pull/399
