### ISSUE TITLE
Analysis doesn't seem to be working for VS 2022.

### ISSUE THREAD

**Issue by ShadowFiendZX** [Acumatica/Acuminator#474]
I pulled down the latest, and compiled, but nothing changed.
I also tried setting several breakpoints throughout Acuminator, but nothing got hit, although all the Unit Tests run successfully.

![image](https://user-images.githubusercontent.com/5325002/206756977-e55bf5ec-1593-4015-850a-8e4741b8c56b.png)

Here's what I think are the relevant settings, in case I'm missing something :
![image](https://user-images.githubusercontent.com/5325002/206757133-eef581e1-4c99-447b-9ea0-1d40536717a9.png)
![image](https://user-images.githubusercontent.com/5325002/206757331-637039bd-98ae-4d2b-a8d2-39701b41b227.png)

I've tried with "Run code analysis in a separate process" both true and false.

VS Version 17.5.0 Preview 1.0

Editing to add that I've also tried [this](https://github.com/Acumatica/Acuminator/blob/dev/docs/dev/Troubleshooting/Troubleshooting.md)

**Comment by SENya1990** [comment]
Hi @ShadowFiendZX, the debug breakpoints did not hit during debug because by default experimental VS performs analysis in a separate process. Please see here for details:
https://github.com/Acumatica/Acuminator/blob/dev/docs/dev/CodingGuidelines/CodingGuidelines.md#debugging-hints

You can disable this behavior in VS options. 

This issue was also reported by some of our devs. Please try repeating steps from the troubleshooting guide:
- uninstall Acuminator and install Clear MEF Caches application
- Make sure that Acuminator extension was deleted by VS in the AppData folders where VS plugins are stored (see the guide for details)
- Open VS and open some solution. Clear MEF caches. It won't hurt to do it a couple of times.
- Install Acuminator and check if analysis works on some solution. 

Note that we do not test Acuminator on VS previews and do not promise that we'll support them.
