### ISSUE TITLE
PX1042_DatabaseQueriesInRowSelecting shows error even in 2023R1 and up

### ISSUE THREAD

**Issue by ShadowFiendZX** [Acumatica/Acuminator#572]
Stepping through the code when running the Unit Tests it seems that in the constructor of `Acuminator.Utilities.Roslyn.Semantic.Symbols.PXCacheSymbols`, `RowSelectingWhileReading` is always null after :

```cs
Type.GetMembers(EventsNames.PXCache.RowSelectingWhileReading)
.OfType<IEventSymbol>()
.FirstOrDefault();
```

because `RowSelectingWhileReading` is internal, and internal members aren't returned by `GetMembers`.

I was able to alter `Acuminator.Tests.Verification.VerificationHelper.CreateProject` to have this :

```cs
CSharpCompilationOptions compileOptions = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
.WithMetadataImportOptions(MetadataImportOptions.All); // compile to a dll
```

However, I'm not sure if there's a way to do that for the analyzer when it's part of the installed extension.

I was also unable to step through the code when debugging an instance of VS, because for some reason the methods weren't getting hit specifically for `DatabaseQueriesInRowSelectingAnalyzer`. I've been able to get other analyzers to hit breakpoints while debugging an instance of VS.

**Comment by SENya1990** [comment]
Hi @ShadowFiendZX 
I'm not sure what problem you are trying to solve. However, it seems to me that the original assumption is incorrect.

> because RowSelectingWhileReading is internal, and internal members aren't returned by GetMembers.

No, Roslyn `GetMembers` returns all type members including even private and internal ones. Is is easy to check. Here I have slightly modified sources for one of the unit tests by adding an internal method `Foo`:
![image](https://github.com/user-attachments/assets/07bb2b99-463e-4ded-af3e-5895c5d61fb3)

Here I look at the modified unit test under debug:
![image](https://github.com/user-attachments/assets/9adc0a5e-76a2-4449-b482-ba69e13741b6)

As you can see, the internal method `Foo` is there.  The same is true for a private member. 

> Acuminator.Utilities.Roslyn.Semantic.Symbols.PXCacheSymbols, RowSelectingWhileReading is always null after :
```cs
Type.GetMembers(EventsNames.PXCache.RowSelectingWhileReading)
.OfType<IEventSymbol>()
.FirstOrDefault();
```
The reason for this is probably not in Roslyn. Acuminator unit tests depend on Acumatica dlls in the lib folder. Which version of Acumatica dlls did you put into the `lib` folder? 

Some Acumatica APIs are newer than others.  `RowSelectingWhileReading` was added to Acumatica 2023r1.  Tests use Acumatica dlls from the `lib` folder and in my case these dlls are from an older version of Acumatica. So, there is nothing strange that older dlls do not contain this symbol and always return `null` for it. 
It is also an important thing to remember. Since Acuminator is used against many different versions of Acumatica, retrieval of symbols for newer Acumatica APIs may return `null` on older Acumatica versions. So, null checks should be performed in most cases on symbol lookup results.

You probably cannot hit a breakpoint in  `DatabaseQueriesInRowSelectingAnalyzer` because starting from Acuminator 3.1.1 this analyzer was disabled for Acumatica 2023r1:
https://github.com/Acumatica/Acuminator/blob/dev/docs/ReleaseNotes.md#acuminator-311
Acumatica runtime was changed and the [PX1042](https://github.com/Acumatica/Acuminator/blob/dev/docs/diagnostics/PX1042.md) diagnostic became redundant.

When you are debugging a unit test, you are debugging code that depends on older Acumatica dlls. That's why in unit test you can debug and test `DatabaseQueriesInRowSelectingAnalyzer` because it is enabled there, If I remember correctly, the analyzer is enabled exactly if the `RowSelectingWhileReading` symbol is null. 

However, when you debug a VS instance, you are probably debugging some of your solutions which reference Acumatica 2023r1 or newer. In this case, `RowSelectingWhileReading` symbol is not null and the analyzer `DatabaseQueriesInRowSelectingAnalyzer` is disabled.

I'm not sure about the reason to change the test infrastructure, but you won't be able to do anything like that to VS. In VS Roslyn analyzers use workspace and compilation are provided by VS, you can't change their options or dependencies and make VS use the changes. 

I hope, that answered your question. If yes, then please resolve the issue.

**Comment by ShadowFiendZX** [comment]
What I was trying to figure out is where the logic for this analyzer was so that I could submit a PR fixing the bug.

Here's a screenshot from a project I have in 24.105.0036 where Acuminator marks an error in a RowSelecting event :

![image](https://github.com/user-attachments/assets/ea0319bf-c5ec-4c86-ad8f-b0f7e7b8fb96)

This is with the latest from the `dev` branch using the dlls from Acumatica 23.206.0006 because I found that one of the external solutions for the Unit Tests wouldn't compile when I used the dlls from Acumatica 24.110.0017, which I believe is because the DAC(s) declared doesn't/don't derive from the new PXBqlTable class.

I bring up the breakpoints for this analyzer not being hit even when debugging VS because the error is shown on the event even though no breakpoint is hit, and as far as I can tell there's no other analyzer that would add that error.

**Comment by SENya1990** [comment]
Thanks for reporting. I checked your example and there is indeed a false alert for PX1042. You were also correct about the analyzer type, it is `DatabaseQueriesInRowSelectingAnalyzer`. 
I'm not sure what is the problem with breakpoints though. I can hit breakpoints set in the analyzer.

Now, to the main part. I was wrong about Roslyn loading private and internal types. I checked under debug and it seems that for external dlls the behavior is different and only public types are loaded. 
This is a very critical issue that affects entire Acuminator, not only `DatabaseQueriesInRowSelectingAnalyzer`. So, it would require a global fix. I will be working on it to include it into the next release.

**Comment by ShadowFiendZX** [comment]
I did quite a lot of googling and [someone](https://github.com/dotnet/roslyn/issues/60360#issuecomment-1078981713) had claimed that getting the Types from `Compilation.GlobalNamespace` would give access to internal members, but after quite a long time of getting all the Unit Tests to pass, it turns out that the result was the same as I originally reported.

![image](https://github.com/user-attachments/assets/2401b48c-c4c7-45b2-ad3c-443f22ac3bed)

[This](https://learn.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies#reference-assemblies-structure) document from Microsoft makes it seem like some specific kinds of internal members aren't emitted although based on how I'd gotten it to work for Unit Tests in my original post, that document might not be relevant.

I did find several posts on GitHub on the topic, such as [this](https://github.com/dotnet/roslyn/issues/5049) one where it seems like this behavior is by design.

After all this effort, I did have the simple idea of checking the Assembly's Attributes for the Acumatica version :

![image](https://github.com/user-attachments/assets/239dc9b8-cb5d-4d15-b6ca-a6f6e874e9f3)

With a bit of effort you could probably find a more intuitive place to put this, and then parse the segments into ints for comparison.

This would likely resolve the specific issue for the bug I reported here, but unfortunately if there's other places in Acuminator that rely on members that aren't returned by Roslyn, then the above methodology wouldn't help.

I should also note that I only tested the above code in my branch where I've rewritten all the logic to use Types gotten from `Compilation.GlobalNamespace` instead of using `Compilation.GetTypeByMetadataName`.

Here's the code for easy copying :

```cs
			if
			(
				Type.ContainingAssembly.GetAttributes().FirstOrDefault(x => x?.AttributeClass?.Name == "AssemblyFileVersionAttribute") is not { } attributeData
				|| attributeData.ConstructorArguments is not { Length: > 0 } constructorArguments
				|| constructorArguments[0].Value is not string { } acumaticaVersion
			)
				return;
```

**Comment by SENya1990** [comment]
@ShadowFiendZX thanks for sharing your investigation. Unfortunately, it is useless to look at version attributes of Acumatica assemblies. They are always the same and equal to 1.0.0.0. This is done deliberately but this means that the version must be determined by other approaches such as a check for the presence of some APIs.

**Comment by ShadowFiendZX** [comment]
The value that's always `1.0.0.0` seems to be Assembly Version, whereas what I was talking about is Assembly File Version which appears to always be set to the expected Acumatica Version, at least in the handful of versions I've checked.

Assuming this doesn't change, this could be a more reliable method of determining the Acumatica Version, as it's within the realm of possibility that a Type or Member you're relying on which was added in version X may be removed sometime in the future in version Y.

IE perhaps the Type you're acquiring and using the null forgiving operator on : `Compilation.GetTypeByMetadataName(TypeFullNames.IViewConfig_Acumatica2018R2)!`

Although, using the version value would still require some care as it may not always be a simple check because :
- R1 previews sometimes fall into the `XX.0YY.ZZZ` range rather than the `XX.1YY.ZZZ` range. IE `18.091.0090` which is a 2018 R1 Preview.
- R2 previews sometimes fall into the `XX.19Y.ZZZ` range rather than the `XX.2YY.ZZZ` range IE `18.191.0050` which is a 2018 R2 Preview, vs `24.200.0118` which is a 2024 R2 Preview.

I've created a PR draft [here](https://github.com/Acumatica/Acuminator/pull/573).
So far in my testing everything works as expected, but feel free to reject and close the PR if this is not the direction you think Acuminator should go in.

**Comment by SENya1990** [comment]
Hi @ShadowFiendZX .
I've spent a lot of time trying to make Roslyn load private and internal metadata. You can read the detailed investigation here:
https://github.com/Acumatica/Acuminator/pull/575#issue-2653372862

In short, it's not possible without very risky hacks that will require rework of the entire Acuminator code base. Moreover, the hacky solution most likely will be unstable, if it will work at all. It will also take a toll on the VS performance. So, I decided to drop the idea to load all metadata, at least until there is an API to do so.

This is still a compromise decision. I feel that in Acumatica framework there can be some private / internal elements that should be analyzed. For example, it is possible to have private graph event handlers for some graph events (although it's not recommended). Still, this shouldn't be too bad:
- The analysis works mostly with the code opened in the code editor. Usually, there is no need to check external dependencies for private members
- Most of the significant code elements in the Acumatica framework usually are exposed as public or protected API

So, I just fixed the check for Acumatica version by using another public API, that was added in 2023r1. The check has to be based on the presence of some new API because there are no version attributes placed on Acumatica assemblies in every context. Some version attributes are placed during the build on production dlls. If we rely on them, Acuminator won't work correctly on developer machines in Acumatica. 

This issue will be closed when the PR with the fix will be merged.
